### ISSUE TITLE
 Cannot find module 'D:\code\vue\django-with-vuejs\my_project\frontend\build\build.js'

### ISSUE THREAD

**Issue by dianxiaopao** [tmpbook/django-with-vuejs#9]
执行 npm run build的一直报错 
Error: Cannot find module 'D:\code\vue\django-with-vuejs\my_project\frontend\build\build.js'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:393:7)
    at startup (bootstrap_node.js:150:9)
    at bootstrap_node.js:508:3

**Comment by tmpbook** [comment]
@dianxiaopao [this commit](https://github.com/tmpbook/django-with-vuejs/commit/a4ca7a455d308aa26037f00c52a4737f0d79dd23)
